lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :get_current_user
    plug :get_current_task
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug :get_current_user
    plug :get_current_task
  end

  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    task_id = get_session(conn, :task_id)
    user = Tasktracker.Accounts.get_user(user_id || -1)
    conn
    |> assign(:current_user, user)
    |> assign(:current_task, task_id)
  end

  def get_current_task(conn, _params) do
    # TODO: Move this function out of the router module.
    task_id = get_session(conn, :task_id)
    conn
    |> assign(:current_task, task_id)
  end


  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/feed", PageController, :feed
    resources "/users", UserController
    resources "/tasks", TaskController
    post "/session", SessionController, :create
    post "/session_task", SessionController, :task_create
    delete "/session", SessionController, :delete
    get "/timeblocks/new", TimeblocksController, :new
    post "/timeblocks/create", TimeblocksController, :web_create
    get "/timeblocks/:id/edit", TimeblocksController, :edit
    put "/timeblocks/:id", TimeblocksController, :web_update
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", TasktrackerWeb do
    pipe_through :api
    resources "/timeblocks", TimeblocksController

  end
end

lib/tasktracker/tracker/timeblocks.ex
defmodule Tasktracker.Tracker.Timeblocks do
  use Ecto.Schema
  import Ecto.Changeset
  alias Tasktracker.Tracker.Timeblocks


  schema "timeblocks" do
    field :end_time, :naive_datetime
    field :start_time, :naive_datetime
    field :start, :boolean, default: false
    belongs_to :task, Tasktracker.Tracker.Task

    timestamps()
  end

  @doc false
  def changeset(%Timeblocks{} = timeblocks, attrs) do
    timeblocks
    |> cast(attrs, [:start_time, :end_time, :task_id, :start])
    |> validate_required([:start_time, :task_id, :end_time, :start])
    |> check_constraint(:end_time, [message: "should be greater than start time", name: "end_time_must_be_greater" ])

  end
end

lib/tasktracker_web/controllers/timeblocks_controller.ex
defmodule TasktrackerWeb.TimeblocksController do
  use TasktrackerWeb, :controller

  alias Tasktracker.Tracker
  alias Tasktracker.Tracker.Timeblocks

  action_fallback TasktrackerWeb.FallbackController

  def index(conn, _params) do
    timeblocks = Tracker.list_timeblocks()
    render(conn, "index.json", timeblocks: timeblocks)
  end

  def create(conn, %{"timeblocks" => timeblocks_params}) do
    timeblocks_param = Enum.drop(timeblocks_params,-2)
    with {:ok, %Timeblocks{} = timeblocks} <- Tracker.create_timeblocks(timeblocks_params) do
      render(conn, "show.json", timeblocks: timeblocks)
    end
  end

  def show(conn, %{"id" => id}) do
    timeblocks = Tracker.get_timeblocks!(id)
    render(conn, "show.json", timeblocks: timeblocks)
  end

  def update(conn, %{"id" => id, "timeblocks" => timeblocks_params}) do
    timeblocks = Tracker.get_timeblocks!(id)

    with {:ok, %Timeblocks{} = timeblocks} <- Tracker.update_timeblocks(timeblocks, timeblocks_params) do
      render(conn, "show.json", timeblocks: timeblocks)
    end
  end

  def delete(conn, %{"id" => id}) do
    timeblocks = Tracker.get_timeblocks!(id)
    # with {:ok, %Timeblocks{}} <- Tracker.delete_timeblocks(timeblocks) do
    #   send_resp(conn, :no_content, "")
    # end
    {:ok, _timeblocks} = Tracker.delete_timeblocks(timeblocks)
    conn
    |> put_flash(:info, "TimeBlock deleted successfully.")
    |> redirect(to: task_path(conn, :show, timeblocks.task_id))
  end

  def new(conn, _params) do
    conn
    |>IO.inspect
    changeset = Tracker.change_timeblocks(%Timeblocks{})
    render(conn, "new.html", changeset: changeset)
  end

  def edit(conn, %{"id" => id}) do
    timeblocks = Tracker.get_timeblocks!(id)
    changeset = Tracker.change_timeblocks(timeblocks)
    render(conn, "edit.html", timeblocks: timeblocks, changeset: changeset)
  end

  def web_create(conn, %{"timeblocks" => timeblocks_params}) do
    case Tracker.create_timeblocks(timeblocks_params) do
      {:ok, timeblocks} ->
        conn
        |> put_flash(:info, "Timeblock created successfully.")
        |> redirect(to: task_path(conn, :show, Tasktracker.Tracker.get_task(timeblocks_params["task_id"])))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def web_update(conn, %{"id" => id, "timeblocks" => timeblocks_params}) do
    timeblocks = Tracker.get_timeblocks!(id)
    case Tracker.update_timeblocks(timeblocks, timeblocks_params) do
      {:ok, timeblocks} ->
        conn
        |> put_flash(:info, "TimeBlock updated successfully.")
        |> redirect(to: task_path(conn, :show, Tasktracker.Tracker.get_task(timeblocks.task_id)))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", timeblocks: timeblocks, changeset: changeset)
    end
  end

end

lib/tasktracker_web/views/timeblocks_view.ex
defmodule TasktrackerWeb.TimeblocksView do
  use TasktrackerWeb, :view
  alias TasktrackerWeb.TimeblocksView

  def render("index.json", %{timeblocks: timeblocks}) do
    %{data: render_many(timeblocks, TimeblocksView, "timeblocks.json")}
  end

  def render("show.json", %{timeblocks: timeblocks}) do
    %{data: render_one(timeblocks, TimeblocksView, "timeblocks.json")}
  end

  def render("timeblocks.json", %{timeblocks: timeblocks}) do
    %{id: timeblocks.id,
      task_id: timeblocks.task_id,
      start_time: timeblocks.start_time,
      end_time: timeblocks.end_time,
      start: timeblocks.start}
  end
end

lib/tasktracker_web/templates/timeblocks/edit.html.eex
<h2>Edit Timeblock</h2>
<h6><strong> Task Title :</strong> <%= Tasktracker.Tracker.get_task(@current_task).title %></h6>

<%= render "form.html", Map.put(assigns, :action, timeblocks_path(@conn, :web_update, @timeblocks)) %>

<span><%= link "Back", to: task_path(@conn, :show, Tasktracker.Tracker.get_task(@current_task)) %></span>

lib/tasktracker_web/templates/timeblocks/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= hidden_input f, :task_id, class: "form-control", value: @current_task %>
  </div>

  <div class="form-group">
    <%= label f, :start_time, class: "control-label" %>
    <%= text_input f, :start_time, type: "datetime", class: "form-control", type: "datetime", placeholder: "YYYY-MM-DD HH:mm:ss" %>
    <span class="error"><%= error_tag f, :start_time %><span>
  </div>

  <div class="form-group">
    <%= label f, :end_time, class: "control-label" %>
    <%= text_input f, :end_time, type: "datetime", class: "form-control", placeholder: "YYYY-MM-DD HH:mm:ss" %>
    <span class="error"><%= error_tag f, :end_time %><span>
  </div>


  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/tasktracker_web/templates/timeblocks/new.html.eex
<h2>New TimeBlock</h2>
<h6><strong> Task Title :</strong> <%= Tasktracker.Tracker.get_task(@current_task).title %></h6>

<%= render "form.html", Map.put(assigns, :action, timeblocks_path(@conn, :web_create)) %>

<span><%= link "Back", to: task_path(@conn, :show, Tasktracker.Tracker.get_task(@current_task)) %></span>